import { IInvoiceContact } from './invoice_contact';
import { IBillItem } from './bills_item';
import { IBillDocument } from './bills_document';

export interface IBillContent
{
    openingInvoice: boolean,
    totalAmount: number,
    totalAmountInBaseCurrency: number,
    payableAccountCode: string,
    taxAmount: number,
    openingDocumentNumber: string,
    warehouseCode: string,
    dropShip: boolean,
    backOrder: boolean,
    status: string,
    customField: string,
    attachmentIds: string,
    contactCode: string,
    purchaseInvoiceType: string,
    linkedDocuments: Array<IBillDocument>,
    supplierInvoiceNo: string,
    purchaseOrderRefNo: string,
    journalEntryCode: string,
    currency: string,
    exchangeRate: number,
    purchaseInvoiceDate: string,
    purchaseInvoiceDueDate: string,
    memo: string,
    attachments: string,
    unitPriceGstInclusive: boolean,
    dueAmount: number,
    totalTdsAmount: string,
    recurring: boolean,
    recurringActivated: boolean,
    purchaseInvoiceAccounts: Array<string>,
    purchaseInvoiceRecurring: string,
    contact: IInvoiceContact,
    purchaseInvoiceProducts: Array<IBillItem>,
    id: number,
    purchaseInvoiceCode: string,
    documentSequenceCode: string,
    knockoffInfo: string,
    draft: boolean,
    paymentStatus: string,
    shipFrom: string,
    shipTo: string,
    billTo: string,
    contactDto: string,
    receiveGoodsStatus: string
  }