import { Inventory } from "./inventory";

export interface Content {
    name : string,
    type : string,
    barcode: string,
    description: string,
    purchasePrice: number,
    salesPrice: number,
    purchaseAccountCode: string,
    salesAccountCode: string,
    purchaseReturnAccountCode: string,
    salesReturnAccountCode: string,
    manufacturingCostAccountCode: string,
    purchaseTaxCode: string,
    salesTaxCode: string,
    purchasePriceTaxInclusive: boolean,
    salesPriceTaxInclusive: boolean,
    stockUom: number,
    images: Array<string>,
    inventory: Inventory,
    categoryCode:string,
    categoryDesc: string,
    taxable: boolean,
    customField: string,
    reorderEnabled: boolean,
    reorderLevel: string,
    documentSequenceCode: string,
    sequenceFormat: string,
    errorMessage: string,
    id: number,
    productId: string,
    active: boolean,
    deleted: boolean,
    bomProductsConfiguration: Array<string>,
    bomAddCostConfiguration: Array<string>
  }
